# fly.toml app configuration file generated for video-recommendations-cyf on 2023-12-05T04:57:05Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "video-recommendations-cyf"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
