[build]
  publish = "server/static"
  command = "npm run build"
[functions]
  directory = "server/api"
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  included_files = ["db/initdb.sql"]
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/index/:splat"
